Added image rendering
Spoutnik97/react-native-prismic-richtext pull request #3
Opened 2021-12-22 11:11 UTC by bitboxer

This PR adds simple image rendering. It will try to display the image with the correct aspect ratio if only height is given.

2021-12-27 16:23 UTC, Spoutnik97 requested changes

2021-12-27 16:23 UTC, Spoutnik97 commented on src/components/ImageView.tsx
> +  console.log('wrapper', wrapperStyle)
Remove the console log

2021-12-27 16:23 UTC, Spoutnik97 commented on src/services.tsx
> +  wrapperStyle: StyleProp<ViewStyle>,
It should be an optional argument

2021-12-27 16:23 UTC, Spoutnik97 commented on src/services.tsx
> +  style: StyleProp<ImageStyle>
It should be optional too

2022-01-03 08:54 UTC, bitboxer commented
Updated the PR 🥳

2022-01-03 17:00 UTC, Spoutnik97 approved these changes

2022-01-03 17:00 UTC, merged